// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHstwdmyA_Hb7jxldL4QDFVKLBlJ_8PL4',
    appId: '1:101536392826:web:6b830dcac16e9a916dbdc3',
    messagingSenderId: '101536392826',
    projectId: 'jackpot-arena-49e79',
    authDomain: 'jackpot-arena-49e79.firebaseapp.com',
    storageBucket: 'jackpot-arena-49e79.appspot.com',
    measurementId: 'G-H8P66J2534',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-uL_H_4bzbqaY4JoY9XkRWi87SJeFBnc',
    appId: '1:101536392826:android:8a73e7d5e2bbdf9a6dbdc3',
    messagingSenderId: '101536392826',
    projectId: 'jackpot-arena-49e79',
    storageBucket: 'jackpot-arena-49e79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKO7aCsYQodmIKjYjCfO0CZW89k1u0lHQ',
    appId: '1:101536392826:ios:33e4e3481a8d39e86dbdc3',
    messagingSenderId: '101536392826',
    projectId: 'jackpot-arena-49e79',
    storageBucket: 'jackpot-arena-49e79.appspot.com',
    iosBundleId: 'com.example.jackpotArena',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKO7aCsYQodmIKjYjCfO0CZW89k1u0lHQ',
    appId: '1:101536392826:ios:33e4e3481a8d39e86dbdc3',
    messagingSenderId: '101536392826',
    projectId: 'jackpot-arena-49e79',
    storageBucket: 'jackpot-arena-49e79.appspot.com',
    iosBundleId: 'com.example.jackpotArena',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHstwdmyA_Hb7jxldL4QDFVKLBlJ_8PL4',
    appId: '1:101536392826:web:2d9d41bb87ae1d4d6dbdc3',
    messagingSenderId: '101536392826',
    projectId: 'jackpot-arena-49e79',
    authDomain: 'jackpot-arena-49e79.firebaseapp.com',
    storageBucket: 'jackpot-arena-49e79.appspot.com',
    measurementId: 'G-BMW0XY9P97',
  );
}
